[paths]
xyz_dir = "/shared/data/nomad2018/train"
load_path = "/shared/data/checkpoints/mlp.pt"
scaler_path = "/shared/data/checkpoints/scaler_mlp.pkl"

[model]
type = "mpl"
batch_size = 64

[inference]
predict = true
test_csv = "/shared/data/nomad2018/test.csv"
output = "predictions_mlp.csv"
